spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///schoolmanager?serverTimezone=UTC
      username: root
      password: root
  mvc:
    static-path-pattern: /static/**
  mail:
    host: smtp.qq.com
    username: 310895302@qq.com
    password: ufsdfrgafgxjcbbc
  redis:
    host: localhost
    port: 6379

server:
  port: 8080


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: cn.yun.entity
